version: "3.7"

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - ./memories:/memories/
      - ./data:/data/
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=$DATABASE_URI
    ports:
      - 5127:5000

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data/

volumes:
  database_data: